### PR TITLE
Merge Feature/ask uwu

### PR DESCRIPTION
**Pull request by Greenscreen23**
I think I'm finally finished. The code was tested in a jsfiddle, but I don't not test the bot yet

### CODE REVIEW

**Comment by Greenscreen23** [comment]
Edit: My bot doesn't answer, don't merge yet

**Comment by Greenscreen23** [comment]
It should work now. (At least my testbot does work)

**Comment by SamyoFox** [comment]
just remembering you, we have a testing bot for Hanako. It's in the Hanako Discord server. You should find the token in the discord dev dashboard (assuming @Fisch03 has added you to the Hanako team)

**Comment by Greenscreen23** [comment]
You're right, I am. Thanks for the hint

**Pull request merged**
