### PR TITLE
Fixed reddit command

### PR DESCRIPTION
**Pull request by Samyocord**
Yes

### CODE REVIEW

**Comment by Fisch03** [comment]
this seems to have mixed with the music command stuff, can you pull from master and resolve the conflicts before i merge this?

**Comment by Samyocord** [comment]
how

**Comment by Fisch03** [comment]
this has both the music command stuff and the reddit commands in it because you worked off of the music branch i guess
should be easy to fix

**Comment by Samyocord** [comment]
oof

**Comment by Fisch03** [comment]
fixed in #58

**Pull request closed without merging**
